[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.mysql"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
numReplicas = 1

[env]
MYSQL_ROOT_PASSWORD = "SecurePass123!"
MYSQL_DATABASE = "jrrg_framework_db"

[mounts]
source = "mysql_data"
destination = "/var/lib/mysql"